# Usando uma imagem base do Node.js para construir a aplicação
FROM node:18 AS build

# Criando o diretório de trabalho
WORKDIR /app

# Instalando dependências
COPY package*.json ./
RUN npm install

# Copiando o código fonte para o diretório de trabalho
COPY . .

# Construindo a aplicação
RUN npm run build

# Usando uma imagem base para servir a aplicação estática com Nginx
FROM nginx:alpine

# Copiando os arquivos construídos para o diretório do Nginx
COPY --from=build /app/build /usr/share/nginx/html

# Expondo a porta que o Nginx vai usar
EXPOSE 80