# Usando uma imagem base do OpenJDK
FROM openjdk:17-jdk-slim

# Copiando o arquivo JAR da aplicação para dentro do contêiner
COPY target/emiteai-0.0.1-SNAPSHOT.jar /app/my-app.jar

# Definindo o diretório de trabalho
WORKDIR /app

# Comando para executar a aplicação
ENTRYPOINT ["java", "-jar", "my-app.jar"]

# Expondo a porta que a aplicação vai usar
EXPOSE 8080